export { discreteLegend } from './discreteLegend'
export { pivotDiscreteLegend } from './pivotDiscreteLegend'
export { colorLegend } from './colorLegend'
export { pivotColorLegend } from './pivotColorLegend'
export { heatmapColorLegend } from './heatmapColorLegend'
